### PR TITLE
Added support for observing ancsAuthorized property on peripheral.

### PR DESCRIPTION
**Pull request by radumvlad**
Added support for `ancsAuthorized` property that was introduced in iOS 13: https://developer.apple.com/documentation/corebluetooth/cbperipheral/3180040-ancsauthorized

### CODE REVIEW

**Comment by radumvlad** [comment]
CI will continue failing since it is using XCode 10.2. Not sure if there's anything I can do for this.

**Comment by radumvlad** [comment]
Unfortunately, generate-mocks.sh only uses iPhone sdk, but not also macOS sdk. I tried changing the script, but just changing the sdk_path doesn't seem to do it, so it beats me. For now I manually added an #if !macOS so the tests run accordingly.

**Comment by minixT** [comment]
I'm working on changes in the generate-mocks.sh script to fix this problem I hope I will manage to complete this soon.

**Comment by radumvlad** [comment]
Thank you @minixT , I will leave this to you.

**Comment by minixT** [comment]
@radumvlad I've updated `generate-mocks.sh` script. Please merge current master branch and regenerate mocks. It should resolve your problems.

**Review by minixT — APPROVED** [review]

**Pull request merged**
