### PR TITLE
Can accessible to 'internal' protection level

### PR DESCRIPTION
**Pull request by kingiol**
I use manager.retrievePeripherals, then get Peripheral
I want to modify Peripheral to ScannedPeripheral
so should use the public init on ScannedPeripheral

### CODE REVIEW

**Comment by Kacper20** [comment]
Hi there,
What’s the reason to convert `Peripheral` to `ScannedPeripheral`? What will you pass as rssi and advertisementData in constructor?

**Comment by kingiol** [comment]
In my app, I use the ScannedPeriperhal.advertisementData.localName to get real BLE name.
App function's parameter type is all ScannedPeriperhal.

**Comment by Kacper20** [comment]
Yeah but when you’re using `retrievePeripheral` call you don’t receive things like advertisementData and RSSI. You’re forced to pass the values yourself. What do you want to pass to this constructor of `ScannedPeripheral` in this case? I’m asking out of curiosity — right now I don’t see it but maybe I’m overlooking something.

Thanks in advance!

**Comment by paweljaneczek** [comment]
Closeing for now. @kingiol If you feel that it is still needed just answer @Kacper20 questions so we will open PR again ;)

**Pull request closed without merging**
