### PR TITLE
Updated RxSwift version to 6

### PR DESCRIPTION
**Pull request by simonbility**

### CODE REVIEW

**Comment by bioche** [comment]
This seems harmless, could we get this merged soon ? ^^

**Review by freak4pc — COMMENTED** [review]
thanks! the podspec needs a major version bump to 7.0.0.
Let me know when that's done and I'll merge and cut a new release.

Thanks!

**Comment by simonbility** [comment]
@freak4pc All Done!

Should i also run `./scripts/generate-docs.sh 7.0.0` ?

**Comment by freak4pc** [comment]
I don't know that script too well but no harm in doing that, I guess :) 
Mainly interested in a compatibility release here.

**Comment by simonbility** [comment]
I also updated the docs now, i was going of the Instructions [here](https://github.com/Polidea/RxBluetoothKit/blob/master/HOW_TO_RELEASE.md)

Thanks for taking care of this!

**Review by freak4pc — APPROVED** [review]

**Comment by cheif** [comment]
Any chance we could get this merged soon? It looks like everythings ready to go to me?

**Comment by amaurydavid** [comment]
Any news on this 7.0.0 release ?

**Review by bramseynhaeve — APPROVED** [review]

**Comment by eliekarouz** [comment]
Any reason why this is blocked? This blocking our migration to Xcode 12.5

**Comment by krezzoid** [comment]
hey,

Is anybody here who could merge this PR? or provide an explanation why this PR was blocked and let us fix it.
@freak4pc, @bartoszstelmaszuk 

Thanks,
Ilya

**Comment by freak4pc** [comment]
Hey all,
I'm not entirely sure why I'm being tagged. This repo is owned by Polidea and not RxSwiftCommunity. I have no admin or publishing rights on it and cannot assist with cutting a release, unfortunately.

**Comment by bioche** [comment]
@freak4pc Well I'm pretty sure it's because you mentioned in earlier comment on this PR you would & I quote "merge & cut a new release" 😂

**Comment by freak4pc** [comment]
Yup, I'm sorry. I'm managing about 30 different projects and repos :) 

If something has "Rx" prefix to it there's a good chance I'm helping maintain it and thought this was the case here as well.
I'm not too sure how I even go to this thread :P 

Anyways, hope you'll work this out soon!

**Comment by krezzoid** [comment]
hey @freak4pc 

sorry, if I mentioned you by mistake, but I did it just because you told:
> Let me know when that's done and I'll merge and cut a new release.
https://github.com/Polidea/RxBluetoothKit/pull/392#pullrequestreview-587856994

so, my thoughts was that you should be able to merge this PR.

As I can see because of silence from Polidea side, repository owner, this PR have quite small chances to be merged.

Best regards,
Ilya

**Comment by bioche** [comment]
Well we probably won't have a response from Polidea soon given the company apparently doesn't exist anymore 😅https://www.linkedin.com/posts/polidea_polidea-was-acquired-by-snowflake-on-feb-activity-6764546785554817025-bgZq

**Comment by krezzoid** [comment]
yep, I found the same news ;)

**Comment by tylerjames** [comment]
So what's the recourse here? I see some of their other libraries have been updated more recently than this Feb 8 announcement. The Android and Flutter versions, for instance, have been updated as recently as this month.

Is there a dominant fork out there that has this PR merged? (it's hard to browse Github forks now)

**Comment by krezzoid** [comment]
hey,

@dariuszseweryn, @mikolak
as I can see you was able to merge PR to Android and Flutter versions of this library.
Could you do the same for iOS version? or maybe you have a contacts from Polidea/Snowflake who can take care on it?

Thanks,
Ilya

**Comment by outsbook** [comment]
May anyone tell me when this version will release?

**Comment by tylerjames** [comment]
Sometime between now and never, it seems

**Comment by eliekarouz** [comment]
Hi @freak4pc, can we fork this under RxSwiftCommunity to maintain it there? I don't think they are going to work on this repo anymore.

**Comment by freak4pc** [comment]
Again @eliekarouz 
> Hey all,
> I'm not entirely sure why I'm being tagged. This repo is owned by Polidea and not RxSwiftCommunity. I have no admin or publishing rights on it and cannot assist with cutting a release, unfortunately.

This is a Polidea project. They are not responsive to this thread and others, it seems. 

I'm not feeling comfortable simply "grabbing" their code and making it a RxSwiftCommunity project. Also, I don't think we should maintain someone else's code this way unless they want to move it and manage it themselves.

**Comment by jfreeley** [comment]
Did a bit of Googling. Polidea was acquired in Feb 2021 and are no longer offering software services, so I'm guessing that's the context for the lack of responses. The Android version of this project is still maintained, probably by an Android dev that still has access.

image

**Comment by freak4pc** [comment]
This project is using Apache license. Nothing prevents anyone from forking and maintaining it.

I don't feel comfortable doing this with RxSwiftCommunity since we only host MIT-licensed projects.

**Review by RadaofTheLight — APPROVED** [review]
BREEZE.rst

**Review by eliekarouz — APPROVED** [review]

**Comment by simonbility** [comment]
Im closing this issue.
I dont have any hopes this will ever get merged.

I (or actually my employer) will keep the fork around but i would suggest to everyone relying on it to create their own fork, since my company has made no commitment to maintain this.

**Pull request closed without merging**
