### PR TITLE
Fixed warnings in Swift 3.1 when using optionals in string interpolation segments

### PR DESCRIPTION
**Pull request by robnadin**

### CODE REVIEW

**Comment by asowers1** [comment]
👍  I would love to have these warnings silenced in my CI :)

**Comment by Kacper20** [comment]
It looks good 👍 Merging to the master.

Thanks!

**Comment by robnadin** [comment]
Would it be possible to release a patch fix with these changes?

**Comment by Kacper20** [comment]
Yes, of course. Doing it right away, thanks!

**Comment by Kacper20** [comment]
@robnadin It's done, you could now get 3.0.13 from Carthage and Cocoapods :)

**Comment by robnadin** [comment]
@Kacper20 thanks! 👍🏻

**Pull request merged**
