### PR TITLE
[WIP] CBPeripheralManager support

### PR DESCRIPTION
**Pull request by AndrewSB**
Moved the commits onto a separate branch, continuation of #30

### CODE REVIEW

**Comment by Kacper20** [comment]
Hi there,
Is there any progress on work on this branch? 
We're preparing migration to Swift 2.3 and Swift 3 and we're making some cleanups and preparing design decisions that are going to affect future shape of the library.

Thanks for letting me know :-)

**Comment by Kacper20** [comment]
I'm closing it for now. In case of interest - please reopen and let us know!

Thanks,

Kacper

**Comment by lexrus** [comment]
Any update on Peripheral mode?

**Comment by Kacper20** [comment]
We're working on this. This will be in 4.0 release. We were stocked a bit, because we want to make breaking changes and remodel API a bit to support peripheral manager in the way that is satisfying to us.

**Pull request closed without merging**
